### ISSUE TITLE
Save merges

### ISSUE THREAD

**Issue by bauwenst** [gautierdag/bpeasy#3]
Thanks for the clean interface. One thing I wonder about is that since the trainer returns only a `Dict[bytes,int]`, there seems to be no trace of the merges that were applied to get to this vocabulary. Having them is required for traditional BPE inference (which in turn is needed to apply e.g. BPE-dropout) and is also just a nice sanity check to see if the algorithm works and/or the data preprocessing did not mess up somewhere along the way. 

They can't be deduced from the vocabulary even when it's in order, since new vocabulary types can often be formed with more than one pair of existing vocabulary types (e.g. it's possible to have a vocabulary `{a, bc, ab, c}` and have `abc` be the next type to be added).

Any thoughts on saving a list of merges too?

**Comment by gautierdag** [comment]
Hey, thanks for the question!

>They can't be deduced from the vocabulary even when it's in order, since new vocabulary types can often be formed with more than one pair of existing vocabulary types (e.g. it's possible to have a vocabulary {a, bc, ab, c} and have abc be the next type to be added).

They can be somewhat recovered - maybe not in the strictly "correct" sense - but it is very much possible to calculate a valid merge list using BPE itself:
 https://github.com/gautierdag/bpeasy/blob/7a6b0cc0ba0b3a1b148269770ff7ce26ce4ed472/bpeasy/convert.py#L8-L29

In fact `tiktoken` and the openai tokenizers don't release merge lists but only provide the dictionary mapping between bytes and int - the o200k base tokenizer is just a simple txt file you can inspect [here](https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken). 

> Having them is required for traditional BPE inference (which in turn is needed to apply e.g. BPE-dropout) and is also just a nice sanity check to see if the algorithm works and/or the data preprocessing did not mess up somewhere along the way.

I can see the perks of that, I don't think BPE-dropout is used enough and a sanity check is always good. That being said, you could always implement BPE-dropout with tiktoken by simply dropping a percentage of the learned tokens (i>256) and encoding your text. 

I would be happy to merge a PR that returns the merge list along with the `Dict[bytes, int]` if a parameter is passed.

**Comment by bauwenst** [comment]
That code snippet to me seems like a completely different inference algorithm that I would think behaves like nothing else I've seen. The merge list it effectively models is much larger than the merge list that was actually learnt -- namely, when a type of n characters is formed, now all n-1 binary merges that could have formed it become available at inference. It's interesting and I will likely experiment with it, but I've never seen this style of BPE inference before.

> In fact tiktoken and the openai tokenizers don't release merge lists but only provide the dictionary mapping between bytes and int (...)

Some models use, as their tokeniser, a BPE vocabulary with greedy left-to-right inference, also called MaxMatch. The BPE vocabulary is then treated as an unstructured set of strings, rather than something halfway between a flat set and a strict hierarchy.

> I would be happy to merge a PR that returns the merge list along with the Dict[bytes, int] if a parameter is passed.

My Rust is too rusty to submit such a PR, but you could leave this issue open if someone else comes along who can.

**Comment by gautierdag** [comment]
> The merge list it effectively models is much larger than the merge list that was actually learnt

🤔I'm not sure that's true? The above method should obtain a single rule for each token in the vocabulary - picking the merge rule greedily using the minimum rank.

Maybe we don't have the same understanding of a merge list?

**Comment by bauwenst** [comment]
Unless I misunderstand the code, what it implies is that if `abcd` is a type in the vocabulary, then the intermediate sequences 
```
... a bcd ...
... ab cd ...
... abc d ...
```
can all be merged into `abcd`. Hence, the formation of `abcd` effectively adds three different merges to the tokeniser's merge list. Meanwhile, while you are vocabularising, only one of those merges can and will ever happen, and that would be the only merge allowed during inference in classical BPE because it would be the only merge that produces `abcd` in the merge list. This can be proved formally as is done in the appendix of [this paper](https://aclanthology.org/2024.naacl-long.324.pdf):
> We now prove that the same type can never be learnt by two different merges within the same vocabularisation phase, or equivalently, that it is impossible to learn a second merge that results in it after a first has been learnt.

**Comment by gautierdag** [comment]
Yes I think there is a misunderstanding here. 

The code would simply return the merge rule with the smallest rank.

```python
# with bc < ab and abc < bcd
mergeable_ranks = {b"a": 0, b"b": 1, b"c": 2, b"d": 3, b"bc": 4, b"ab": 5, b"abc": 6, b"bcd": 7, b"abcd": 8}
print(bpe(mergeable_ranks, b"abcd", max_rank=8))
# > [b'abc', b'd']

# with bc < ab and bcd < abc
mergeable_ranks = {b"a": 0, b"b": 1, b"c": 2, b"d": 3, b"bc": 4, b"ab": 5, b"abc": 7, b"bcd": 6, b"abcd": 8}
print(bpe(mergeable_ranks, b"abcd", max_rank=8))
# > [b'a', b'bcd']

# with ab < bc - then abc always gets merged first
mergeable_ranks = {b"a": 0, b"b": 1, b"c": 2, b"d": 3, b"bc": 5, b"ab": 4, b"abc": 7, b"bcd": 6, b"abcd": 8}
print(bpe(mergeable_ranks, b"abcd", max_rank=8))
# > [b'abc', b'd']

```

So for `abcd` it would only return a single merge rule depending on the rank of the previous tokens -- merging greedily the tokens with smallest rank. 

Note you would never find merge rule `ab cd` in this case (because I haven't included `"cd"` as a token)

**Comment by bauwenst** [comment]
Yes, of course the same segmentation is always returned for the same string, it's deterministic inference. My point is about applying the tokeniser to *all* possible words.

If the string `abcd` is tokenised as the full token `abcd` with the last step combining `a bcd`, that classically means that **if** you encounter the sequence of tokens 

`... ab cd ...` 

inside the loop of the `bpe()` function for any word containing the letters `...abcd...` (say, `zzzabcdzzz`), that sequence of tokens is **not** merged into `abcd` because a different merge was learnt for it. With the above implementation, `abcd` would still be merged despite `ab cd` not having been learnt.

**Comment by gautierdag** [comment]
>If the string abcd is tokenised as the full token abcd with the last step combining a bcd, that classically means that if you encounter the sequence of tokens
> ... ab cd ...
> inside the loop of the bpe() function for any word containing the letters ...abcd... (say, zzzabcdzzz), that sequence of tokens is not merged into abcd because a different merge was learnt for it. With the above implementation, abcd would still be merged despite ab cd not having been learnt.

Apologies but I'm still struggling to understand what the issue is here so I'll try to follow your example. 

If I have a learned vocab:
```python
mergeable_ranks = {b"a": 0, b"b": 1, b"c": 2, b"d": 3, b"bc": 4, b"ab": 5, b"abc": 7, b"bcd": 6, b"abcd": 8}
```
This would then learn the merge rule (`[b'a', b'bcd']`) for token 8 (`b"abcd"`). Again note that I don't have the token `cd` here just for the example.

Now you want to tokenize a longer string like `zzzabcdzzz`? Well given the vocab this would be indeed tokenize it as `<z><z><z><abcd><z><z><z>` - assuming a byte-level fallback for `z`.

Note the `bpe()` function here is *only* used to recover merge rules in a greedy manner from the learned token rankings. Hence why there is an assert here to ensure the merge rules are indeed merges between two known tokens:
https://github.com/gautierdag/bpeasy/blob/7a6b0cc0ba0b3a1b148269770ff7ce26ce4ed472/bpeasy/convert.py#L87

This `bpe` function is not used or implemented for general inference - I defer all inference to `tiktoken` or `huggingface` as this library is only focused with training. 

In the case of learning the tokens from `zzzabcdzzz` it would honestly depend on the string its frequency and frequencies of the subwords. It could very well be that `abcd` is so common that it gets tokenized first and then `zzzabcd` gets learned and then `zzzabcd`.. so on.

**Comment by bauwenst** [comment]
> This `bpe` function is not used or implemented for general inference - I defer all inference to tiktoken or huggingface as this library is only focused with training.

Well, its purpose is still to generate a merge list that will be used for general inference. Anyway, I didn't realise there was a function in your library that already generates a merge list, and that's sufficient as a sanity check for me.

https://github.com/gautierdag/bpeasy/blob/7a6b0cc0ba0b3a1b148269770ff7ce26ce4ed472/bpeasy/convert.py#L70-L93
